=== redelmann/ninth-age-xml/rulebook.dtd
<?xml version="1.0" encoding="utf8" ?>
<!ENTITY % Content "definition | reference | link | table | sequence | list | figure | illustration | important | br">

<!ELEMENT chapter (#PCDATA | section | subsection | note | %Content;)*>
<!ELEMENT section (#PCDATA | subsection | note | %Content;)*>
<!ELEMENT subsection (#PCDATA | note | %Content;)*>
<!ELEMENT note (#PCDATA | %Content;)*>
<!ELEMENT definition (#PCDATA | note | %Content;)*>
<!ELEMENT table (headers?, row*)>
<!ELEMENT headers (header*)>
<!ELEMENT header (#PCDATA | reference | link)*>
<!ELEMENT row (header?, cell*)>
<!ELEMENT cell (#PCDATA | %Content;)*>
<!ELEMENT sequence (item*)>
<!ELEMENT item (#PCDATA | %Content;)*>
<!ELEMENT list (item*)>
<!ELEMENT figure (image, caption)>
<!ELEMENT image EMPTY>
<!ELEMENT caption (#PCDATA | reference | link)*>
<!ELEMENT illustration (image*)>
<!ELEMENT reference (#PCDATA | %Content;)*>
<!ELEMENT document (chapter+)>
<!ELEMENT br EMPTY>
<!ELEMENT link (#PCDATA)*>
<!ELEMENT important (#PCDATA | %Content;)*>

<!ATTLIST chapter title CDATA #REQUIRED>
<!ATTLIST section title CDATA #REQUIRED>
<!ATTLIST subsection title CDATA #REQUIRED>
<!ATTLIST note title CDATA #REQUIRED>
<!ATTLIST item title CDATA #IMPLIED>
<!ATTLIST definition name ID #REQUIRED>
<!ATTLIST reference name CDATA #REQUIRED>
<!ATTLIST reference type (example|reference) "reference">
<!ATTLIST image source CDATA #REQUIRED>
<!ATTLIST link to CDATA #REQUIRED>
<!ATTLIST caption title CDATA #REQUIRED>
<!ATTLIST figure name ID #REQUIRED>
<!ATTLIST table title CDATA #IMPLIED>
<!ATTLIST headers title CDATA #IMPLIED>

=== redelmann/ninth-age-xml/rulebook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "rulebook.dtd">
<document>
  
  <!-- CHAPTER : Models, Units and Formations -->

  <chapter title="Models, Units and Formations">
    <section title="Models">
      <definition name="model">
        <reference name="model">Models</reference> represent fighting warriors, monsters and spellcasters. Everything that is standing on the same <reference name="base">base</reference> is considered the same <reference name="model">model</reference> (e.g. a dragon and its rider or a <reference name="cannon">Cannon</reference> and its three crewmen are considered a single <reference name="model">model</reference>).
      </definition>

      <subsection title="Bases and Base Contact">
        <definition name="base">
          All <reference name="model">models</reference> are placed on a square, rectangular or round <reference name="base">base</reference>. The extent of the <reference name="model">model</reference> is considered to be its <reference name="base">base</reference>.</definition>

          <br />

          <reference name="base">Base</reference> sizes are given as two measurements in millimetres: front/width x side/length. (For example, the normal <reference name="cavalry" type="example">cavalry</reference> <reference name="base">base</reference> is 25x50mm). In some rare cases <reference name="model">models</reference> have round <reference name="base">bases</reference>. In these cases, only as single measurement is given: the diameter of the <reference name="base">base</reference>. (For example, a standard <reference name="war_machine" type="example">War Machine</reference> base is a round 60mm base).
        
          <br />

        <definition name="base_contact">
          Two <reference name="model">models</reference> are considered to be <reference name="base_contact">in base contact</reference> with each other if their <reference name="base">bases</reference> are touching one another, including corner to corner contact.
        </definition>
      </subsection>

      <subsection title="Multipart Models">
        <definition name="multipart_model">
          <definition name="model_part">
            <reference name="model">Models</reference> with more than one <reference name="characteristics_profile">Characteristics Profile</reference> are called <reference name="multipart_model">Multipart Models</reference>. For example, a cavalry model is a model with two parts (the rider and its mount), a chariot can be described as a single model consisting of five parts (two horses, two crewmen and one chariot chassis), while a normal foot soldier is a model which consists of a single part. Each part of such a model has its own <reference name="characteristics_profile">Characteristics Profile</reference> and can be referred to as a "<reference name="model_part">model part</reference>".
          </definition>
        </definition>
      </subsection>
    </section>
    <section title="Units">
        All <reference name="model">models</reference> are part of a unit. <definition name="unit">A <reference name="unit">unit</reference> is either a group of <reference name="model">models</reference> deployed in a formation consisting of <definition name="rank"><reference name="rank">ranks</reference> (along the width of the unit)</definition> and <definition name="file"><reference name="file">files</reference> (along the length of the unit)</definition> or a single <reference name="model">model</reference> operating on its own.</definition> Whenever a rule, ability, spell and so on affects a unit, all <reference name="model">models</reference> in the <reference name="unit">unit</reference> are affected. When forming a <reference name="unit">unit</reference>, all <reference name="model">models</reference> in the <reference name="unit">unit</reference> must be perfectly aligned <reference name="base_contact">in base contact</reference> with each other and face the same direction. <definition name="incomplete_rank">All <reference name="rank">ranks</reference> must always have the same width, except <definition name="incomplete_rear_rank">the last <reference name="rank">rank</reference> which can be shorter than the other <reference name="rank">ranks</reference>; if so, this is called an <reference name="incomplete_rear_rank">incomplete rear rank</reference>.  Note that it's perfectly fine for the last <reference name="rank">rank</reference> to have empty gaps in it, as long as the <reference name="model">models</reference> are aligned with those of the other <reference name="rank">ranks</reference>.</definition></definition>
      <subsection title="Rank-and-File">
        <definition name="rank_and_file">
          Normal <reference name="model">models</reference> in a <reference name="unit">unit</reference> are called <reference name="rank_and_file">Rank-and-File</reference> <reference name="model">models</reference> <reference name="rank_and_file">(R&amp;F)</reference>. <reference name="character">Characters</reference> are not <reference name="rank_and_file">R&amp;F</reference> <reference name="model">models</reference>, but all other <reference name="model">models</reference> are.
        </definition>
      </subsection>
      <subsection title="Full Ranks">
        <definition name="full_rank">
          A <reference name="full_rank">Full Rank</reference> is any <reference name="rank">rank</reference> which is at least 5 <reference name="model">models</reference> wide. Some <reference name="unit">units</reference> (such as <reference name="monstrous_infantry">Monstrous Infantry</reference>) require fewer than 5 <reference name="model">models</reference> to form a <reference name="full_rank">Full Rank</reference>, see <reference name="troop_type">Troop Types</reference> section for details.
        </definition>
      </subsection>
      <subsection title="Horde Formation">
        <definition name="horde_formation">
          <reference name="unit">Units</reference> in <reference name="rank">ranks</reference> of 10 or more <reference name="model">models</reference> (6 or more in the case of <reference name="monstrous_rank">Monstrous Ranks</reference>) are considered to be in <reference name="horde_formation">Horde Formation</reference>.
        </definition>
      </subsection>
      <subsection title="Footprint">
        <definition name="footprint">
          A <reference name="unit">unit</reference>'s <reference name="footprint">Footprint</reference> is the area occupied by the combined <reference name="base">bases</reference> of all the <reference name="model">models</reference> in a <reference name="unit">unit</reference>.
        </definition>
      </subsection>
      <subsection title="Centre of Unit">
        <definition name="centre_of_unit">
A <reference name="unit">unit</reference>'s <reference name="centre_of_unit">Centre</reference> is defined by drawing an imaginary rectangle around the outer edges of the unit's <reference name="footprint">Footprint</reference>. The Centre of this box is considered to be the <reference name="centre_of_unit">Centre of the unit</reference>.
        </definition>
      </subsection>
      <subsection title="Unit Facing and Arcs">
        <definition name="arc">
          A <reference name="unit">unit</reference> has 4 <reference name="arc">arcs</reference>: front, rear, and two flanks. Each arc is determined by extending a straight line from the corners of the unit's <reference name="base">bases</reference>, in a 135° angle from the unit's front (for the front arc), rear (for the rear arc) or flanks (for the flank arcs), see <link to="figure_1">figure 1</link>. <reference name="unit">Units</reference> on round <reference name="base">bases</reference> don't have <reference name="arc">arcs</reference> (they can draw <reference name="line_of_sight">Line of Sight</reference> from any point on their bases, in any direction).
        </definition>
      </subsection>
      <figure id="figure_1">
        <image source="centre_footprint_and_arcs.png" />
        <caption title="Figure 1">
          This unit has 3 <reference name="rank">ranks</reference> and 5 <reference name="file">files</reference>. The <reference name="base">base</reference> on the side is a <reference name="character">Character</reference> with a <reference name="mismatching_base">Mismatching base</reference> that has joined the <reference name="unit">unit</reference>. The last <reference name="rank">rank</reference> is <reference name="incomplete_rank">incomplete</reference> and only contains 3 <reference name="model">models</reference>. The <reference name="unit">unit</reference>'s <reference name="footprint">Footprint</reference> is the area occupied by the <reference name="base">bases</reference> of all the <reference name="model">models</reference> within the <reference name="unit">unit</reference> (the green area). The <reference name="centre_of_unit">Centre of the unit</reference> is the centre of the rectangle drawn around its outer edges (marked with a red x). The front, side and rear <reference name="arc">arcs</reference> are defined by using a 135° angle from the <reference name="unit">unit</reference>'s edges.
        </caption>
      </figure>
    </section>
  </chapter>


  <!-- CHAPTER : General Principles -->

  <chapter title="General Principles">
    <section title="Turn">
      <definition name="game_turn">
